### ISSUE TITLE
Front-End

### ISSUE THREAD

**Issue by mariatheresahqs** [gegen07/gegen07.github.io#2]
Germano, seu site está ficando muito bacana!
Pra deixar ele um pouco mais responsivo tenta usar [boostrap](https://getbootstrap.com/docs/4.0/components/navbar/). E se precisar de algum toque pode chamar aqui. ;)

**Comment by gegen07** [comment]
Sim, o próximo passo é deixá-lo responsivo e adicionar internacionalização ao site. Obrigado pelas dicas!

**Comment by gegen07** [comment]
O site já está com o layout responsivo! [gegen07.github.io](gegen07.github.io).

**Comment by mariatheresahqs** [comment]
Ficou show!! 😃 
Ah, se vc for pra Puc mesmo será colega de um amigo meu. Vou dar um toque nele pra ele te procurar. 
😊
